apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app: app-c
  name: app-c
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: app-c
  strategy:
    blueGreen:
      activeService: app-c
      autoPromotionEnabled: true
      previewService: app-c-preview
  template:
    metadata:
      labels:
        app: app-c
    spec:
      containers:
        - image: codedev.jfrog.io/pov-sandbox-fd396f0/app-c:acdfb75
          imagePullPolicy: Always
          name: app-c
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
      restartPolicy: Always